"""Add foo

Revision ID: f85985c0e86d
Revises: 6d14a9e7b315
Create Date: 2022-04-15 20:11:45.726449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f85985c0e86d'
down_revision = '6d14a9e7b315'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('col1', sa.String(length=256), nullable=True),
    sa.Column('col2', sa.String(length=256), nullable=True),
    sa.Column('col3', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foo_id'), 'foo', ['id'], unique=False)
    op.create_index(op.f('ix_foo_rocks'), 'foo', ['rocks'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_foo_rocks'), table_name='foo')
    op.drop_index(op.f('ix_foo_id'), table_name='foo')
    op.drop_table('foo')
    # ### end Alembic commands ###
